
name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.5'
      - name: Flutter pub get
        run: flutter pub get
      - name: Flutter create platforms
        run: flutter create .
      - name: Ensure google services plugin
        run: |
          sed -i '/dependencies {/a \        classpath "com.google.gms:google-services:4.3.15"' android/build.gradle || true
          echo "apply plugin: 'com.google.gms.google-services'" >> android/app/build.gradle || true
      - name: Build APK
        run: flutter build apk --release
      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: reco-apk
          path: build/app/outputs/flutter-apk/app-release.apk
